version: '3.8'

services:
    flask:
        build: .
        enviroment:
            FLASK_APP = flaskr
            FLASK_ENV = development
        volumes:
            - type: bind
              source: .
              target: /flask-tutorial
        ports:
            - "5001:5000"
        tty: true
