name: learn-github-actions
on: 
  push:
    branches: [ Studying-Actions ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      WORKPLACE: ${{github.workspace}}

    steps:
    - name: Clone
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./.github/workflows

